### PR TITLE
just stop already

### PR DESCRIPTION
**Pull request by crappyrules**
the forking guide was a mistake.  Spoonfeeding people with zero coding knowledge to create a network is becoming cancerous.  If people should be making their own network, let them figure it out on their own.  It will help them build character and they will have to have a small amount of coding knowledge to achieve success.

### CODE REVIEW

**Comment by ExtraHash** [comment]
as much as i'd like to agree, imo more forks = more people knowing about and using the TurtleCoin software.

thats what it's all about right?

**Comment by zpalmtree** [comment]
No, it's more people using broken versions of the software, wasting developers time with questions which could be discovered in 5 minutes of googling, and bizarre drama. I can name maybe 3 forks who actually have programmed anything out of 50 who have been a complete waste of time, money, and brainpower.

**Comment by ExtraHash** [comment]
isn't this the whole no press is bad press argument? maybe they're not contributing code but more users are aware of trtl because of it

**Comment by krruzic** [comment]
TurtleCoin is shitcoin help desk and IT support thanks to the forking guide.

**Comment by TheDevMinerTV** [comment]
I really really hate to say this, but @crappyrules is right.
There are (a lot of) TRTL forks that either die, waste a lot of time and/or money of the people using them or are simply not in the mind of Turtlecoin goal of easy and secure cryptocurrencies.

A few occurences:
- TLRM: privating opensource code
- TRTG: threatening Turtlecoin
- KEG: same as above

**Comment by TheDevMinerTV** [comment]
I'd say, merge this.

**Comment by crappyrules** [comment]
No, don't merge this.  Just delet the entire repo.  let people fork wallets, tools, etc.  But let them struggle if they cannot figure out how to do a simple fork of the network.  This will weed out the riff raff that do not have any business creating a network and stealing resources from miners because they cannot even manage to keep their network up and running.  There are enough trtl forks already that are making the code base look like a joke due to lack of simple support.  This is what is happening  https://imgur.com/a/iXHkwMH

**Pull request closed without merging**
